# Clippy configuration for MCP Proxy

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Documentation requirements
missing-docs-in-crate-items = true

# Performance lints
too-many-arguments-threshold = 7
type-complexity-threshold = 250

# Style preferences
enum-variant-names-threshold = 3
single-char-binding-names-threshold = 4

# Allow certain patterns that are common in async/web code
avoid-breaking-exported-api = false
